### ISSUE TITLE
Wakabot timing error

### ISSUE THREAD

**Issue by Acorn221** [IzStriker/WakaBot#71]
Hi, sometimes the time is off with the wakabot, 
![image](https://github.com/IzStriker/WakaBot/assets/28987083/0ec8e2d8-290a-4be1-8feb-98b881792f2c)
is how long it says I have used it, but on the wakatime website, it says this:
![image](https://github.com/IzStriker/WakaBot/assets/28987083/bb4b3341-a888-4d35-9eb4-b0fa6d97cac9)
![image](https://github.com/IzStriker/WakaBot/assets/28987083/fb590b2c-3c40-4a9d-87bb-ec1e1840a0db)

**Comment by IzStriker** [comment]
> Leaderboards only update a few times per day, and always lag behind your public profile. 

https://wakatime.com/faq#leaderboard-vs-dashboard
